<b>1.Forget Gate Layer: </b> $f_{t} = \sigma (W_{f} . [h_{t-1},x_{t}] + b_{f})$

<b>2.Input Gate Layer: </b> $i_{t} = \sigma (W_{i} . [h_{t-1},x_{t}] + b_{i})$

<b>3.Candidate value Layer: </b> $\widetilde{C}_{t} = a_{t} = g_{t} = tanh(W_{c} . [h_{t-1},x_{t}] + b_{c})$

<b>4.Output Gate Layer: </b> $O_{t} = \sigma (W_{o} . [h_{t-1},x_{t}] + b_{o})$


<b>New State: $C_{t} = f_{t} \ast C_{t-1} + i_{t-1} \ast \widetilde{C}_{t-1}$ </b><br>
<b>Output at t: </b> $h_{t} = tanh(c_{t})\ast O_{t}$

### Dimensions to be used
<b>input: </b>x $\in$ (5,4)<br>
$h_{t} \in$ (5,1)<br>
$[x,h_{t}] \in$ (5,5)<br>

$w_{f},w_{i},w_{c},w_{o} \in$ (5,5)

$b_{f},b_{i},b_{c},b_{o} \in$ (1,1)

A Single sentence is taken for example with 5 words and having and embedding dimension of 4. each word is fed to the lstm cell in an unrolled rnn cell against another translated foreign word having a dimention of 1. 

|  input| word  	|     Embedding Dimension 4  	    	    	     	
|:------|:----------|:-----:|:-----:|:-----:|:-----:| 
| x[0] 	| possibly 	| 1.2 	| 0.2 	| 5.1 	| 1.3 	|
| x[1] 	| i        	| 0.2 	| 1.1 	| 3.1 	| 1.9 	|
| x[2] 	| shall    	| 5.0 	| 2.1 	| 1.2 	| 5.1 	|
| x[3] 	| come     	| 3.0 	| 1.4 	| 2.7 	| 1.6 	|
| x[4] 	| tommorow 	| 2.3 	| 1.4 	| 3.6 	| 6.4 	|

|      	| target 	|     	|
|------	|--------	|-----	|
| h[0] 	| awe    	| 1.2 	|
| h[1] 	| su     	| 0.2 	|
| h[2] 	| inh    	| 5.0 	|
| h[3] 	| meiyh  	| 3.0 	|
| h[4] 	| niyah  	| 2.3 	|

In [1]:
import numpy as np

In [2]:
# ###### If you need to use this comment out every line in below cell ######

# #### Data Loading ###
# #### X=[x,h(t)] ##### dim=(10,6) #####
# def get_data():
#     X=np.zeros(shape=(5,5),dtype=np.float32)
#     print("4 float value as input =========> 1 float value as label")
#     for i in range(len(X[:,0])):
#         for j in range(len(X[0,:])):
#             X[i,j]=float(input())
#     print("[x,h(t)]: ",X.shape)
#     print("=======>Random weight value")
#     w_f=np.random.rand(1,5)
#     b_f=np.random.rand(1,1)
    
#     w_i=np.random.rand(1,5)
#     b_i=np.random.rand(1,1)
    
#     w_c=np.random.rand(1,5)
#     b_c=np.random.rand(1,1)
    
#     w_o=np.random.rand(1,5)
#     b_o=np.random.rand(1,1)
    
#     print("w_f: ",w_f.shape,"w_i:",w_i.shape,"w_c:",w_c.shape,"w_o:",w_o.shape)
#     W=dict()
#     b=dict()
#     W={"w_f":w_f,
#       "w_i":w_i,
#       "w_c":w_c,
#       "w_o":w_o}
#     B={"b_f":b_f,
#       "b_i":b_i,
#       "b_c":b_c,
#       "b_o":b_0}
#     return X,W,B

# X,W,B=get_data()

In [3]:
#### If you need to use this comment out each line in above cell #######


#### Testing values #####
X=[[1,2,0.5],
  [0.5,3,1.25]]
X=np.array(X,dtype=np.float32)

w_c=[[0.45,0.25,0.15]]
b_c=[[0.2]]
w_c=np.array(w_c,dtype=np.float32)
b_c=np.array(b_c,dtype=np.float32)

w_i=[[0.95,0.8,0.8]]
b_i=[[0.65]]
w_i=np.array(w_i,dtype=np.float32)
b_i=np.array(b_i,dtype=np.float32)

w_f=[[0.7,0.45,0.1]]
b_f=[[0.15]]
w_f=np.array(w_f,dtype=np.float32)
b_f=np.array(b_f,dtype=np.float32)

w_o=[[0.6,0.4,0.25]]
b_o=[[0.1]]
w_o=np.array(w_o,dtype=np.float32)
b_o=np.array(b_o,dtype=np.float32)

W=dict()
B=dict()
W={"w_f":w_f,
  "w_i":w_i,
  "w_o":w_o,
  "w_c":w_c}
B={"b_f":b_f,
  "b_i":b_i,
  "b_o":b_o,
  "b_c":b_c}

In [4]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

### Forward Pass

In [5]:
#### defined globally ####
dim_embed=2
s=np.zeros(shape=(dim_embed+1,1),dtype=np.float32)
h=np.zeros(shape=(dim_embed+1,1),dtype=np.float32)
f=np.zeros(shape=(dim_embed+1,1),dtype=np.float32)
i=np.zeros(shape=(dim_embed+1,1),dtype=np.float32)
o=np.zeros(shape=(dim_embed+1,1),dtype=np.float32)
a=np.zeros(shape=(dim_embed+1,1),dtype=np.float32)
## h[-1]=0.0

In [6]:
def forward_pass(sample_X,W,B):
    print("Forward-PASS: %d"%t)
    f[t]=sigmoid(np.matmul(W["w_f"],np.concatenate((sample_X,h[t-1]),axis=0).reshape(dim_embed+1,-1))+B["b_f"])
    i[t]=sigmoid(np.matmul(W["w_i"],np.concatenate((sample_X,h[t-1]),axis=0).reshape(dim_embed+1,-1))+B["b_i"])
    o[t]=sigmoid(np.matmul(W["w_o"],np.concatenate((sample_X,h[t-1]),axis=0).reshape(dim_embed+1,-1))+B["b_o"])
    a[t]=np.tanh(np.matmul(W["w_c"],np.concatenate((sample_X,h[t-1]),axis=0).reshape(dim_embed+1,-1))+B["b_c"])
    
    #save the state
    s[t]=np.multiply(f[t],s[t-1])+np.multiply(i[t],a[t])
    #save the output
    h[t]=np.multiply(np.tanh(s[t]),o[t])
    
    print(f[t],i[t],o[t],a[t],s[t],h[t])
    return 0

In [7]:
i.shape

(3, 1)

In [8]:
X[:,0:-1]

array([[1. , 2. ],
       [0.5, 3. ]], dtype=float32)

In [9]:
### start the forward pass for the sentence with 5 words #####
t=0
for k in range(len(X[:,-1])):
    t=k
    forward_pass(X[t,0:-1],W,B)

Forward-PASS: 0
[0.85195273] [0.96083426] [0.8175745] [0.8177541] [0.78572613] [0.5363134]
Forward-PASS: 1
[0.87030196] [0.981184] [0.8499334] [0.84980404] [1.5176332] [0.7719812]


In [10]:
X

array([[1.  , 2.  , 0.5 ],
       [0.5 , 3.  , 1.25]], dtype=float32)

### Backward Pass

Formulas used: <br>
$\delta h_{t} = \Delta_{t} + \Delta_{h_{t}}$ <br>
$\Delta_{h_{t}}=U^{T}.\delta_{gate}$

where,<br>
$\Delta_{t} = \Delta$ error at time t ===> ($O-\widehat{O}$)<br>
$\Delta_{h_{t}}$ = error propagated from next step(t+1)<br>

$\delta s_{t} = \delta h_{t}\odot o_{t}\odot(1 - tanh^{2}(s_{t})) + \delta s_{t+1} \odot f_{t+1} $<br>
$\delta a_{t} = \delta s_{t} \odot i_{t} \odot (1 - a_{t}^{2})$<br>
$\delta i_{t} = \delta s_{t} \odot a_{t} \odot i_{t} \odot (1 - i_{t})$<br>
$\delta f_{t} = \delta s_{t} \odot s_{t-1} \odot f_{t} \odot (1 - f_{t})$<br>
$\delta o_{t} = \delta h_{t} \odot tanh(s_{t}) \odot o_{t} \odot (1 - o_{t})$<br>

In [11]:
def backward_pass(sample_X,DELTA_t,DELTA_ht,delta_stt):
    print("Backward Pass:%d"%t)
    delta_ht = DELTA_t + DELTA_ht
    delta_st = np.multiply(np.multiply(delta_ht,o[t]),(1-np.tanh(np.tanh(s[t])))) + np.multiply(delta_stt,f[t+1])
    delta_at = np.multiply(np.multiply(delta_st,i[t]),(1-np.power(a[t],2)))
    delta_it = np.multiply(np.multiply(np.multiply(delta_st,a[t]),i[t]),(1-i[t]))
    delta_ft = np.multiply(np.multiply(np.multiply(delta_st,s[t-1]),f[t]),(1-f[t]))
    delta_ot = np.multiply(np.multiply(np.multiply(delta_ht,np.tanh(s[t])),o[t]),(1-o[t-1]))
    
    #using approximation
    delta_zt=np.array([delta_at, delta_it, delta_ft, delta_ot]).reshape(4,-1)
    
    #wt row sequence at,it,ft,ot
    ### column_major_[zt]*row_major_[X]
    delta_wt=np.matmul(delta_zt,sample_X.reshape(1,-1))
    delta_B=delta_zt
    
    ##update DELTA_ht to be propagated to next state
    DELTA_ht=np.matmul(U,delta_zt)
    return delta_wt,delta_B,delta_st,DELTA_ht

In [12]:
print("Input dataset X")
print(X[:,0:-1])

Input dataset X
[[1.  2. ]
 [0.5 3. ]]


### formula to calculate change in weight / bias value w.r.t error

$f_{t} = \sigma (W_{f} . [h_{t-1},x_{t}] + b_{f})$<br>
$i_{t} = \sigma (W_{i} . [h_{t-1},x_{t}] + b_{i})$<br>
$a_{t} = tanh(W_{c} . [h_{t-1},x_{t}] + b_{c})$<br>
$O_{t} = \sigma (W_{o} . [h_{t-1},x_{t}] + b_{o})$<br>
<hr>
$z_{t} = [ a_{t},i_{t},f_{t},o_{t} ] = W \ast [X,h[t-1]] + B $ ............(1)<br> 
<hr>

Derivating the above equation for $\delta w \; \& \; \delta b \; using \; \delta z$

$\delta z_{t} = [ \delta a_{t},\delta i_{t}, \delta f_{t}, \delta o_{t} ]^{T}$ <br>

$\delta w_{t} = \delta z_{t} \ast [X,h[t-1]]_{t}$<br>
$\delta b_{t} = \delta z_{t} $<br>


In [13]:
### start the backward pass from last word to first word and calculate 𝛿w,𝛿b wrt 𝛿error ######
## Total(𝛿w,𝛿b) 
total_delta_wt=np.zeros(shape=(4,dim_embed+1),dtype=np.float32)
total_delta_B=np.zeros(shape=(4,1),dtype=np.float32)

## Weight matrix for pred
U=np.array([W["w_c"][:,-1], W["w_i"][:,-1], W["w_f"][:,-1], W["w_o"][:,-1]]).reshape(1,-1)

## Original labels
label=np.array(X[:,-1]).reshape(dim_embed,1)

In [14]:
print("predicted: ",h.reshape(1,-1))
print("Actual: ",label.reshape(1,-1))

predicted:  [[0.5363134 0.7719812 0.       ]]
Actual:  [[0.5  1.25]]


In [15]:
delta_stt=0.0 #next state change
DELTA_ht=0.0 #Initial output change
while t>=0:
    sample_X=np.concatenate((X[t,0:-1],h[t-1]),axis=0)
    
    ## 𝛿error=pred-original
    DELTA_t=h[t] - label[t]
    
    delta_wt,delta_B,delta_stt,DELTA_ht=backward_pass(sample_X,DELTA_t,DELTA_ht,delta_stt)
    total_delta_wt+=delta_wt
    total_delta_B+=delta_B
    t=t-1

Backward Pass:1
Backward Pass:0


In [16]:
print(total_delta_wt)

[[-0.04559817 -0.15315111 -0.01661359]
 [-0.00380239 -0.01117041 -0.00095615]
 [-0.00503912 -0.03023473 -0.0054051 ]
 [-0.02700757 -0.188653   -0.03610405]]


In [17]:
print(total_delta_B)

[[-0.06108686]
 [-0.0046938 ]
 [-0.01007824]
 [-0.06066704]]


### Update the weight based on SGD function with learning rate λ = 0.01
$W^{new}=W - \lambda \ast W^{total\_delta\_wt}$<br>
$B^{new}=B - \lambda \ast B^{total\_delta\_B}$

In [18]:
learning_rate=0.001
def update_parameter(matA,matB):
    return matA - (learning_rate * matB)

In [19]:
### Dont change the order of formation of array
weight=np.array([W["w_c"],W["w_i"],W["w_f"],W["w_o"]]).reshape(4,-1)
bias=np.array([B["b_c"],B["b_i"],B["b_f"],B["b_o"]]).reshape(4,-1)
print("=====================Old values=======================")
print("weights=======")
print(weight)
print("bias==========")
print(bias)

=====================Old values=======================
weights=======
[[0.45 0.25 0.15]
 [0.95 0.8  0.8 ]
 [0.7  0.45 0.1 ]
 [0.6  0.4  0.25]]
bias==========
[[0.2 ]
 [0.65]
 [0.15]
 [0.1 ]]


In [20]:
weight=update_parameter(weight,total_delta_wt)
bias=update_parameter(bias,total_delta_B)

In [21]:
print("=====================new values=======================")
print("weights=======")
print(weight)
print("bias==========")
print(bias)

=====================new values=======================
weights=======
[[0.4500456  0.25015315 0.15001662]
 [0.9500038  0.80001116 0.80000097]
 [0.70000505 0.45003024 0.1000054 ]
 [0.600027   0.40018865 0.2500361 ]]
bias==========
[[0.20006108]
 [0.6500047 ]
 [0.15001008]
 [0.10006067]]


## Resources

[Understanding](http://www.wildml.com/2015/10/recurrent-neural-networks-tutorial-part-3-backpropagation-through-time-and-vanishing-gradients/) backpropagation through time.

Reference to a [Numerical Example.](https://medium.com/@aidangomez/let-s-do-this-f9b699de31d9) 

Mathematical expression used for derivations. [Slides](http://arunmallya.github.io/writeups/nn/lstm/index.html#/)